http:
  routers:
    catalog-router:
      rule: "PathPrefix(`/api`) && Header(`Accept`, `application/vnd.bookstore.v1+json`)"
      entryPoints:
        - web
      service: catalog-service
    swagger-router:
      rule: "PathPrefix(`/swagger-ui`) || PathPrefix(`/v3/api-docs`)"
      entryPoints:
        - web
      service: catalog-service
    keycloak-router:
      rule: "PathPrefix(`/auth`)"
      entryPoints:
        - web
      service: keycloak-service
  services:
    catalog-service:
      loadBalancer:
        servers:
          - url: "http://catalog-service:8080"
    keycloak-service:
      loadBalancer:
        servers:
          - url: "http://keycloak:8080"
