entryPoints:
  web:
    address: ":8080"

providers:
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true

accessLog:
  format: json
  fields:
    headers:
      defaultMode: drop
      names:
        X-Request-Id: keep
        Authorization: redact
